# Most of the parameters will be imported from the training config
src:
  ckpt: 'ckpt/asr_dlhlp_sd0/best_att.pth'
  config: 'config/dlhlp/asr_dlhlp.yaml'
data:
  corpus:
    name:  'Dlhlp'
    dev_split: ['dev']
    test_split: ['test']
decode:
  beam_size: 20
  min_len_ratio: 0.01
  max_len_ratio: 0.30
  lm_path: 'ckpt/lm_dlhlp_sd0/best_ppx.pth'
  lm_config: 'config/dlhlp/lm_dlhlp.yaml'
  lm_weight: 0.5
  ctc_weight: 0.0
hparas:
  optimizer: 'Adadelta'